steps:
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
      - gcloud
      - functions
      - deploy
      - vf-acs-func-$LOCATION-test
      - --region=$LOCATION
      - --source=.
      - --entry-point=myBackgroundFunction
      - --trigger-bucket=vf-$LOCATION-test
      - --runtime=python310

    #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #  args:
    #  - gcloud
    #  - functions
    #  - deploy
    #  - vf-acs-func-$LOCATION-test
    #  - --region=$LOCATION
    #  - --source=.
    #  - --entry-point=myBackgroundFunction
    #  - --trigger-bucket=vf-$LOCATION-test
    #  - --runtime=python310
    
    #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    #  args:
    #  - gcloud
    #  - functions
    #  - deploy
    #  - vf-acs-func-$LOCATION-test
    #  - --region=$LOCATION
    #  - --source=.
    #  - --entry-point=myBackgroundFunction
    #  - --trigger-bucket=vf-$LOCATION-test
    #  - --runtime=python310

#ADD EXTRA STEPS HERE TO ACCOUNT FOR ALL 3 regions. I.e 2 more steps for the different regions