steps:
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
      - gcloud
      - functions
      - deploy
      - vf-acs-func-test
      - --region=europe-west2
      - --source=.
      - --trigger-bucket=vf-europe-west2-test
      - --runtime=python310