SYSTEMS:
    source: "vf"
    target: "acs"

GCPPROJECT: "inspired-bus-362513"

CLOUDSTORAGE:
    inputfolder: 'Input/'
    archivefolder: 'Archive/'
    failurefolder: 'Failure/'
    
ACS:
    url: "https://httpbin.org/post"

